name: tekmatic_incubator_module
services:
  tekmatic_incubator_module:
    container_name: tekmatic_incubator_module
    image: ghcr.io/ad-sdl/tekmatic_incubator_module
    build:
      context: .
      tags:
        - ghcr.io/ad-sdl/tekmatic_incubator_module:latest
        - ghcr.io/ad-sdl/tekmatic_incubator_module:dev
    volumes:
      - ./src:/home/app/tekmatic_incubator_module/src
      - ./tests:/home/app/tekmatic_incubator_module/tests
    command: python -m tekmatic_incubator_module --port 2000
    ports:
      - 2000:2000
#####################
# WEI Core Services #
#####################
  tekmatic_incubator_wei_server:
    image: ghcr.io/ad-sdl/wei
    container_name: tekmatic_incubator_wei_server
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./workcells:/workcells
    command: python3 -m wei.server --workcell /workcells/test.workcell.yaml
    depends_on:
      - tekmatic_incubator_wei_redis
  tekmatic_incubator_wei_redis:
    image: redis
    container_name: tekmatic_incubator_wei_redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
